name: tests

on:
  - push
  - pull_request

jobs:
  test:
    name: Test package
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        go:
          - "1.11"
          - "1.13"
          - "1.14"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        env:
          GOPATH: ${{ runner.workspace }}
          # GO111MODULE: "on"
      
      - name: Go setup
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go}}
        env:
          GOPATH: ${{ runner.workspace }}
          # GO111MODULE: "on"
      - name: Run test
        env:
          GOPATH: ${{ runner.workspace }}
          # GO111MODULE: "on"
        run: |
          go get -u github.com/grokify/html-strip-tags-go
          go test ./...
      - if: failure()
        run: ls -R
      